#!/usr/bin/env python3
"""Aggregate ``rewriter_report/data/*.json`` into ``rewriter_report/REPORT.md``.

    python3 rewriter_report/tools/build_report.py           # write REPORT.md
    python3 rewriter_report/tools/build_report.py --check   # validate only

Records are merged by (theory, id); when two units describe the same rule,
the more severe confidence wins and both sources are listed.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEVELS = ["suspect", "low", "medium", "high", "n/a"]
REQUIRED = ["id", "theory", "location", "coverage", "confidence", "rationale"]
COVERAGE = {"rare", "rare-multi", "theory-rewrite", "macro-elaborated",
            "evaluate", "none"}


def load() -> tuple[list[dict], list[dict], list[str]]:
    units, rules, errors = [], [], []
    for path in sorted(glob.glob(os.path.join(ROOT, "data", "*.json"))):
        name = os.path.basename(path)
        try:
            d = json.load(open(path))
        except json.JSONDecodeError as e:
            errors.append(f"{name}: invalid JSON: {e}")
            continue
        units.append({k: d.get(k) for k in ("unit", "source_rev", "binary")}
                     | {"file": name, "n": len(d.get("rules", []))})
        for r in d.get("rules", []):
            miss = [k for k in REQUIRED if not r.get(k)]
            if miss:
                errors.append(f"{name}: {r.get('id', '?')}: missing {miss}")
            if r.get("confidence") not in LEVELS:
                errors.append(f"{name}: {r.get('id')}: bad confidence "
                              f"{r.get('confidence')!r}")
            if r.get("coverage") not in COVERAGE:
                errors.append(f"{name}: {r.get('id')}: coverage "
                              f"{r.get('coverage')!r} not in {sorted(COVERAGE)}")
            for p in r.get("probes") or []:
                if not os.path.exists(os.path.join(ROOT, p)):
                    errors.append(f"{name}: {r.get('id')}: missing probe {p}")
            rules.append(r | {"_unit": d.get("unit") or name[:-5]})
    return units, rules, errors


def merge(rules: list[dict]) -> list[dict]:
    out: dict[tuple, dict] = {}
    for r in rules:
        key = (r.get("theory"), r.get("id"))
        if key not in out:
            out[key] = r | {"_units": [r["_unit"]]}
            continue
        cur = out[key]
        cur["_units"].append(r["_unit"])
        if LEVELS.index(r["confidence"]) < LEVELS.index(cur["confidence"]):
            out[key] = r | {"_units": cur["_units"]}
    return list(out.values())


def _cell(s) -> str:
    if s is None:
        return ""
    if isinstance(s, list):
        s = ", ".join(map(str, s))
    return str(s).replace("|", "\\|").replace("\n", " ")


def sweeps() -> list[str]:
    """Summarize ``runs/*.json``, written by ``probe.py --ethos --out``."""
    runs = sorted(glob.glob(os.path.join(ROOT, "runs", "*.json")))
    if not runs:
        return []
    L = ["## Probe sweeps", "",
         "Every probe re-run on each binary by `tools/probe.py --ethos`. "
         "*Clean* means unsat with no trust step and accepted by ethos against "
         "the source revision's CPC signature; ethos failures on old binaries "
         "include version skew. A disagreement counts only when neither solver "
         "reported an error.", "",
         "| Binary | Probes | unsat | sat | clean | trust | ethos rejects "
         "| proof errors | disagree |",
         "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
    dis: dict[str, list[str]] = {}
    for path in runs:
        d = json.load(open(path))
        ps = d["probes"]
        m = re.search(r"git ([0-9a-f]{7,})", d["versions"]["cvc5"])
        b = m.group(1) if m else os.path.basename(path)[:-5]
        uns = [p for p in ps if p["cvc5"] == "unsat"]
        trust = [p for p in uns if p.get("trust")]
        clean = [p for p in uns if not p.get("trust") and p.get("ethos_ok")]
        rej = [p for p in uns if not p.get("trust") and "ethos" in p
               and not p.get("ethos_ok")]
        perr = [p for p in uns if p.get("proof_error")]
        dis[b] = sorted(p["file"] for p in ps if p["disagree"])
        L.append(f"| {b} | {len(ps)} | {len(uns)} | "
                 f"{sum(p['cvc5'] == 'sat' for p in ps)} | {len(clean)} | "
                 f"{len(trust)} | {len(rej)} | {len(perr)} | {len(dis[b])} |")
    L.append("")
    for b, fs in dis.items():
        if fs:
            L += [f"Disagreements on {b}: " + ", ".join(f"`{f}`" for f in fs),
                  ""]
    return L


def render(units: list[dict], rules: list[dict]) -> str:
    theories = sorted({r["theory"] for r in rules})
    L = ["# Rewriter faithfulness report", "",
         "Generated by `tools/build_report.py` from `data/*.json`; do not edit "
         "by hand. The method and confidence levels are in "
         "[METHOD.md](METHOD.md).", ""]
    revs = sorted({u["source_rev"] for u in units if u.get("source_rev")})
    bins = sorted({h for u in units for h in
                   re.findall(r"git ([0-9a-f]{7,})", u.get("binary") or "")})
    L += [f"Source revision: {', '.join(revs) or '?'}. "
          f"Reviewers' probe binaries: {', '.join(bins) or '?'}.", ""]

    L += ["## Summary", "", "| Theory | " + " | ".join(LEVELS) + " | total |",
          "| --- |" + " ---: |" * (len(LEVELS) + 1)]
    for t in theories + ["all"]:
        rs = [r for r in rules if t == "all" or r["theory"] == t]
        cnt = [sum(r["confidence"] == lv for r in rs) for lv in LEVELS]
        lab = "**all**" if t == "all" else t
        L.append(f"| {lab} | " + " | ".join(map(str, cnt)) + f" | {len(rs)} |")
    L.append("")

    L += ["| Theory | " + " | ".join(sorted(COVERAGE)) + " |",
          "| --- |" + " ---: |" * len(COVERAGE)]
    for t in theories:
        rs = [r for r in rules if r["theory"] == t]
        L.append(f"| {t} | " + " | ".join(
            str(sum(r["coverage"] == c for r in rs)) for c in sorted(COVERAGE))
            + " |")
    L.append("")

    L += sweeps()

    sus = [r for r in rules if r["confidence"] == "suspect"]
    L += ["## Suspect rules", ""]
    if not sus:
        L += ["None.", ""]
    for r in sorted(sus, key=lambda r: (r["theory"], r["id"])):
        L += [f"### `{r['id']}` ({r['theory']})", "",
              f"- **Location:** `{r['location']}`",
              f"- **Dispatch:** {_cell(r.get('dispatch'))}",
              f"- **Proof rules:** {_cell(r.get('proof_rules'))}",
              f"- **Guard gap:** {_cell(r.get('guard_gap'))}",
              f"- **Witness:** {_cell(r.get('witness'))}",
              f"- **Probes:** {_cell(r.get('probes'))} "
              f"({_cell(r.get('probe_result'))})",
              f"- **Rationale:** {_cell(r.get('rationale'))}", ""]

    for t in theories:
        L += [f"## {t}", "",
              "| Rule | Confidence | Coverage | Proof rules | Rationale |",
              "| --- | --- | --- | --- | --- |"]
        rs = sorted((r for r in rules if r["theory"] == t),
                    key=lambda r: (LEVELS.index(r["confidence"]), r["id"]))
        for r in rs:
            L.append(f"| `{_cell(r['id'])}` | {r['confidence']} | "
                     f"{r['coverage']} | {_cell(r.get('proof_rules'))} | "
                     f"{_cell(r.get('rationale'))} |")
        L.append("")

    L += ["## Units", "", "| Unit | File | Records | Source rev |",
          "| --- | --- | ---: | --- |"]
    for u in units:
        L.append(f"| {u['unit']} | `data/{u['file']}` | {u['n']} | "
                 f"{u.get('source_rev') or ''} |")
    return "\n".join(L) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    units, rules, errors = load()
    for e in errors:
        print(f"warning: {e}", file=sys.stderr)
    merged = merge(rules)
    if not a.check:
        with open(os.path.join(ROOT, "REPORT.md"), "w") as f:
            f.write(render(units, merged))
        print(f"wrote REPORT.md: {len(merged)} rules from {len(units)} units")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
