"""Command line for the supported-fragment analysis.

    python3 -m dokimasia.fragment theories <cvc5>   # per theory, available vs blocked
    python3 -m dokimasia.fragment check    <cvc5>   # is the fragment enforced?
    python3 -m dokimasia.fragment doc      <cvc5>   # emit docs/fragment.md
"""

from __future__ import annotations

import argparse
import json

from .fragment import EXPERT_OPTIONS, NONKIND_AXIS, THEORY_OPTIONS, scan


def cmd_theories(args) -> int:
    f = scan(args.cvc5)
    rows = []
    for th in sorted(f.by_theory()):
        a, b = f.safe_fragment(th)
        rows.append((th, a, b))
    if args.json:
        print(json.dumps([{"theory": t, "available": a, "blocked": b}
                          for t, a, b in rows], indent=2))
        return 0
    print("Term kinds per theory, under --safe-mode=safe\n")
    print(f"  {'theory':<14}{'available':>10}{'blocked':>9}   how blocked")
    for th, a, b in rows:
        how = ""
        if b:
            mech = {f.blocked_in_safe_mode(k)[1].split(" (")[0] for k in b}
            how = ", ".join(sorted(mech))
        print(f"  {th:<14}{len(a):>10}{len(b):>9}   {how}")
    if args.theory:
        a, b = f.safe_fragment(args.theory)
        print(f"\n  {args.theory} — available ({len(a)}):")
        for k in a:
            print(f"    {k}")
        print(f"  {args.theory} — blocked ({len(b)}):")
        for k in b:
            print(f"    {k:<28} {f.blocked_in_safe_mode(k)[1]}")
    return 0


def cmd_check(args) -> int:
    f = scan(args.cvc5)
    unc = f.uncovered_expert_options()
    if args.json:
        print(json.dumps({"uncovered": [{"option": o, "axis": ax, "where": w}
                                        for o, ax, w in unc]}, indent=2))
        return 1 if unc else 0
    print("Is the safe-mode fragment enforced?\n")
    print("  Three mechanisms, in decreasing order of reliability:\n")
    print(f"    1. whole-theory sweep — {', '.join(sorted(THEORY_OPTIONS))}")
    print("       illegal_checker walks every Kind and blocks those belonging to")
    print("       a disabled theory. Complete by construction.")
    print("    2. per-kind deny list — hand-maintained, one insert per kind.")
    print("    3. theory-local guards — a LogicException thrown from ppRewrite.\n")
    cov = f.expert_coverage()
    print("  Expert extensions safe mode disables, and the kinds they gate:\n")
    for o in sorted(EXPERT_OPTIONS):
        ks = cov.get(o, [])
        print(f"    {o:<16} {len(ks):>3} kinds" + (f"   e.g. {ks[0]}" if ks else ""))
    if unc:
        print(f"\n  {len(unc)} gate no term kind at all:\n")
        for o, axis, where in unc:
            print(f"    {o:<12} restricts the {axis} — {where}")
            if o in NONKIND_AXIS:
                print(f"                 {NONKIND_AXIS[o][2]}")
        print("\n  This is the substantive result: **the supported fragment is not")
        print("  expressible as a list of kinds.** An option may restrict the logic")
        print("  (higher-order) or a type (experimental floating-point sorts)")
        print("  instead, and no table records those. Any statement of the form")
        print("  'safe mode supports exactly these kinds' is therefore incomplete.")
    return 1 if unc else 0


def cmd_doc(args) -> int:
    f = scan(args.cvc5)
    out = ["# The supported fragment", "",
           "*Generated by `python3 -m dokimasia.fragment doc <cvc5>`. Do not edit.*",
           "",
           "Which term `Kind`s may appear in an assertion under `--safe-mode=safe`,",
           "per theory. Type-level kinds (sorts) are excluded: this is about terms.",
           "", "## Per theory", "",
           "| theory | available | blocked | how blocked |",
           "| --- | --- | --- | --- |"]
    for th in sorted(f.by_theory()):
        a, b = f.safe_fragment(th)
        mech = sorted({f.blocked_in_safe_mode(k)[1].split(" (")[0] for k in b}) if b else []
        out.append(f"| `{th}` | {len(a)} | {len(b)} | {', '.join(mech) or '—'} |")
    out += ["", "## Blocked kinds, and what blocks them", ""]
    for th in sorted(f.by_theory()):
        _a, b = f.safe_fragment(th)
        if not b:
            continue
        out.append(f"### `{th}`")
        out.append("")
        for k in b:
            out.append(f"- `{k}` — {f.blocked_in_safe_mode(k)[1]}")
        out.append("")
    unc = f.uncovered_expert_options()
    if unc:
        out += ["## Restrictions that are not about kinds", "",
                "These options safe mode disables gate no term kind. The fragment",
                "is therefore **not expressible as a kind list alone**.", "",
                "| option | restricts | where |", "| --- | --- | --- |"]
        for o, axis, where in unc:
            why = NONKIND_AXIS.get(o, (None, None, ""))[2]
            out.append(f"| `{o}` | the {axis} | `{where}` |")
            if why:
                out.append(f"| | | {why} |")
        out.append("")
    text = "\n".join(out) + "\n"
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {args.out}")
    else:
        print(text)
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="python3 -m dokimasia.fragment",
        description="What logical fragment cvc5 supports, per theory, and whether "
                    "it is enforced.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    t = sub.add_parser("theories", help="per theory, available vs blocked")
    t.add_argument("cvc5"); t.add_argument("--theory")
    t.add_argument("--json", action="store_true")
    t.set_defaults(func=cmd_theories)
    c = sub.add_parser("check", help="is the fragment enforced?")
    c.add_argument("cvc5"); c.add_argument("--json", action="store_true")
    c.set_defaults(func=cmd_check)
    d = sub.add_parser("doc", help="emit the fragment document")
    d.add_argument("cvc5"); d.add_argument("--out")
    d.set_defaults(func=cmd_doc)
    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
